[package]
name = "kill-desktop"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
edition = "2015"

[dependencies]
nix = "0.11"
xcb = "0.8"

[dependencies.clap]
version = "2"
default-features = false

[dependencies.failure]
# -= derive
version = "0.1"
default-features = false
features = ["std"]

[profile.release]
lto = true
