[package]
name = "kill-desktop"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

[dependencies]
dirs = "1"
failure = "0.1"
nix = "0.11"
regex = "1"
serde_derive = "1"
serde = "1"
toml = "0.4"
xcb = "0.8"

[profile.release]
lto = true
