[package]
name = "kill-desktop"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
log = "0.4"
pretty_env_logger = "0.2"
xcb = "0.8"
